name: product cicd
on:
    pull_request:
        branches:
            - main

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  IMAGE_NAME: varun213/product
  DEPLOYMENT_FILE: Kubernetes/deployment.yaml
  IMAGE_TAG: ${{ github.run_id }}

jobs:
    code-quality:
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up go 1.22
              uses: actions/setup-go@v2
              with:
                go-version: 1.22

            - name: Run golangci-lint
              continue-on-error: true
              uses: golangci/golangci-lint-action@v6
              with:
                version: latest
                args: ./...
                
   
     
    build-and-push:
      if: github.event_name == 'pull_request'
      runs-on: ubuntu-latest
      #needs: code-quality
      name: Build and Push Docker Image
      steps:
        - name: Checkout Code
          uses: actions/checkout@v3

        - name: Log in to Docker Hub
          run: echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin

        - name: Build and Push Image
          run: |
          
            docker build -t $IMAGE_NAME:$IMAGE_TAG .
            docker push $IMAGE_NAME:$IMAGE_TAG
                       
    update-deployment:
      if: github.event_name == 'pull_request'
      runs-on: ubuntu-latest
      needs: build-and-push
      name: Update Kubernetes Deployment File and Commit to Stage
      steps:
        - name: Checkout Code
          uses: actions/checkout@v3
          with:
            ref: ${{ github.head_ref }}

        - name: Set Git Config
          run: |
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"

        - name: Update deployment image
          run: |
            sed -i "s|image:.*|image: $IMAGE_NAME:$IMAGE_TAG|" $DEPLOYMENT_FILE
            git add $DEPLOYMENT_FILE
            git commit -m "Update image to $IMAGE_NAME:$IMAGE_TAG [ci skip]" || echo "No changes to commit"
            git push origin ${{ github.head_ref }}
 

                 